CREATE TABLE subscription (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(255) NOT NULL,
                              cost DECIMAL(10,2) NOT NULL,
                              renewal_date DATE NOT NULL,
                              category VARCHAR(100)
);

INSERT INTO subscription (name, cost, renewal_date, category) VALUES('Netflix',15.99, DATEADD('DAY',10, CURRENT_DATE), 'Streaming'),
                                                                    ('Spotify',9.99, DATEADD('DAY',5, CURRENT_DATE), 'Music'),
                                                                    ('Gym Membership',40.00, DATEADD('DAY',20, CURRENT_DATE), 'Fitness'),
                                                                    ('Adobe Creative Cloud',20.99, DATEADD('DAY',2, CURRENT_DATE), 'Software'),
                                                                    ('Amazon Prime',14.99, DATEADD('DAY',15, CURRENT_DATE), 'Shopping');